export const CPU_CORES_FOR_CUSTOM_SOLUTION = 2;
export const MAX_ATTEMPT_WAITING_OLD_TXS = 20;
export const MAX_ATTEMPT_WAITING_NEW_TX = 3;
export const ATTEMPT_PERIOD_MS = 3000;
export const MAX_ORDERS_RUNNING = 2;
export const MINUTES_IN_HOUR = 60;
export const MILLISECONDS_IN_DAY = 24 * 60 * 60 * 1000;
export const TX_REVERTED_BY_EVM_ERROR = 'Transaction has been reverted by the EVM';
export const DEFAULT_PCCS_SERVICE = 'https://pccs.superprotocol.io';
export const BACKEND_URL_DEFAULT = 'https://bff.superprotocol.com/graphql';
export const BLOCKCHAIN_RPC_URL_DEFAULT = 'https://opbnb.superprotocol.com';
export const SMART_CONTRACT_ADDRESS_DEFAULT = '0x3C69ea105Fc716C1Dcb41859281Aa817D0A0B279';
export const BASE64_CHECK_REGEX = /^[A-Za-z0-9+/]{1,}={0,3}$/;
export const JWT_CHECK_REGEX = /(^[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*$)/;
export const CONFIG_DEFAULT_FILENAME = './config.json';
export const DEFAULT_TEE_AMOUNT_FOR_APPROVE = 1e10;
export const MINUTES_IN_YEAR = 60 * 24 * 365;
