name: Create binary files for every supported platform
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    build:
        runs-on: ${{ matrix.os }}
        env:
            GITHUB_PAT: ${{ secrets.NPM_TOKEN_GH }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup Go environment
              uses: actions/setup-go@v2.1.5
              with:
                  go-version: 1.17
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 17.4.0
                  architecture: x64
            - name: Install dependencies
              run: npm install
            - name: Build binary for macOS
              if: ${{ runner.os == 'macOS' }}
              run: >
                  npm run build:macos
                  && mv ./dist/spctl ./dist/sp-publisher-macos-x64
            - name: Build binary for Windows
              if: ${{ runner.os == 'Windows' }}
              run: >
                npm run build:win
                && mv ./dist/spctl ./dist/sp-publisher-windows
            - name: Build binary for Linux
              if: ${{ runner.os == 'Linux' }}
              run: >
                  npm run build:linux
                  && mv ./dist/spctl ./dist/sp-publisher-linux-x64
            - name: "Save build results for release job"
              uses: actions/upload-artifact@v2
              with:
                  name: release
                  path: dist/spctl-*
                  retention-days: 1
    create-release:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: "Download artifacts"
              uses: actions/download-artifact@v2
              with:
                  name: release
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      spctl-macos-x64
                      spctl-linux-x64
