name: Build
on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: macos-12 # Intel Mac
                      output: spctl-macos-x64
                    - os: ubuntu-20.04
                      output: spctl-linux-x64
                    - os: macos-14 # M1 Mac
                      output: spctl-macos-arm64
                    - os: windows-latest
                      output: spctl-win32-x64
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 16.15.0
                  scope: super-protocol
            - name: Install dependencies
              run: npm ci
            - name: Build binary
              run: |
                  npm run build
                  mv ./dist/spctl ./dist/${{ matrix.output }}
            - name: "Save build results for release job"
              uses: actions/upload-artifact@v2
              with:
                  name: release
                  path: dist/spctl-*
                  retention-days: 1
    create-release:
        runs-on: ubuntu-20.04
        needs: [build]
        steps:
            - name: "Download artifacts"
              uses: actions/download-artifact@v2
              with:
                  name: release
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      spctl-macos-x64
                      spctl-linux-x64
                      spctl-macos-arm64
                      spctl-win32-x64
