name: Create binary files for every supported platform
on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10.8
            - name: Setup Go environment
              uses: actions/setup-go@v2.1.5
              with:
                  go-version: 1.17
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 16.15.0
                  architecture: x64
                  scope: super-protocol
            - name: Install dependencies
              run: yarn --frozen-lock
            - name: Build binary for macOS
              if: ${{ runner.os == 'macOS' }}
              run: >
                  npm run build:mac
                  && mv ./dist/spctl ./dist/spctl-macos-x64
            - name: Build binary for Linux
              if: ${{ runner.os == 'Linux' }}
              run: >
                  npm run build:linux
                  && mv ./dist/spctl ./dist/spctl-linux-x64
            - name: "Save build results for release job"
              uses: actions/upload-artifact@v2
              with:
                  name: release
                  path: dist/spctl-*
                  retention-days: 1
    create-release:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: "Download artifacts"
              uses: actions/download-artifact@v2
              with:
                  name: release
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      spctl-macos-x64
                      spctl-linux-x64
