name: Run all necessary checks for pull request

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup Go environment
              uses: actions/setup-go@v2.1.5
              with:
                  go-version: 1.18
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 16.15.0
                  architecture: x64
                  scope: super-protocol
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build:prepare
            - name: Unit tests
              run: npm run test
